// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// An [admission allowlist
/// pattern][google.cloud.binaryauthorization.v1.AdmissionWhitelistPattern]
/// exempts images from checks by [admission
/// rules][google.cloud.binaryauthorization.v1.AdmissionRule].
///
/// [google.cloud.binaryauthorization.v1.AdmissionRule]: <doc:AdmissionRule>
/// [google.cloud.binaryauthorization.v1.AdmissionWhitelistPattern]: <doc:AdmissionWhitelistPattern>
public struct AdmissionWhitelistPattern: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// An image name pattern to allowlist, in the form `registry/path/to/image`.
  /// This supports a trailing `*` wildcard, but this is allowed only in
  /// text after the `registry/` part. This also supports a trailing `**`
  /// wildcard which matches subdirectories of a given entry.
  public var namePattern: Swift.String = Swift.String()

  /// Initialize a new instance of `AdmissionWhitelistPattern`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdmissionWhitelistPattern().with { $0.namePattern = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.AdmissionWhitelistPattern"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
