// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An [attestor][google.cloud.binaryauthorization.v1.Attestor] that attests to
/// container image artifacts. An existing attestor cannot be modified except
/// where indicated.
///
/// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
public struct Attestor: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name, in the format:
  /// `projects/*/attestors/*`. This field may not be updated.
  public var name: Swift.String = Swift.String()

  /// Optional. A descriptive comment.  This field may be updated.
  /// The field may be displayed in chooser dialogs.
  public var description: Swift.String = Swift.String()

  /// Output only. Time when the attestor was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. A checksum, returned by the server, that can be sent on update
  /// requests to ensure the attestor has an up-to-date value before attempting
  /// to update it. See https://google.aip.dev/154.
  public var etag: Swift.String = Swift.String()

  public var attestorType: OneOf_AttestorType? = nil

  /// Initialize a new instance of `Attestor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Attestor().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case description = "description"
    case userOwnedGrafeasNote = "userOwnedGrafeasNote"
    case updateTime = "updateTime"
    case etag = "etag"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.description = try container.decode(Swift.String.self, forKey: .description)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)

    var attestorType: OneOf_AttestorType? = nil
    let attestorTypeCheckAndSet = {
      if attestorType != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'attestorType'"))
      }
      attestorType = $0
    }
    if let userOwnedGrafeasNote = try container.decodeIfPresent(
      UserOwnedGrafeasNote?.self, forKey: .userOwnedGrafeasNote)
    {
      try attestorTypeCheckAndSet(.userOwnedGrafeasNote(userOwnedGrafeasNote))
    }
    self.attestorType = attestorType
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)

    if let choice = self.attestorType {
      switch choice {
      case .userOwnedGrafeasNote(let value):
        try container.encode(value, forKey: .userOwnedGrafeasNote)
      }
    }
  }

  public enum OneOf_AttestorType: Codable, Equatable, Sendable {
    /// This specifies how an attestation will be read, and how it will be used
    /// during policy enforcement.
    indirect case userOwnedGrafeasNote(UserOwnedGrafeasNote?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.Attestor"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
