// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An [attestor public key][google.cloud.binaryauthorization.v1.AttestorPublicKey] that will be used to verify
/// attestations signed by this attestor.
///
/// [google.cloud.binaryauthorization.v1.AttestorPublicKey]: <doc:AttestorPublicKey>
public struct AttestorPublicKey: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. A descriptive comment. This field may be updated.
  public var comment: Swift.String = Swift.String()

  /// The ID of this public key.
  /// Signatures verified by BinAuthz must include the ID of the public key that
  /// can be used to verify them, and that ID must match the contents of this
  /// field exactly.
  /// Additional restrictions on this field can be imposed based on which public
  /// key type is encapsulated. See the documentation on `public_key` cases below
  /// for details.
  public var id: Swift.String = Swift.String()

  public var publicKey: OneOf_PublicKey? = nil

  /// Initialize a new instance of `AttestorPublicKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttestorPublicKey().with { $0.comment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case comment = "comment"
    case id = "id"
    case asciiArmoredPgpPublicKey = "asciiArmoredPgpPublicKey"
    case pkixPublicKey = "pkixPublicKey"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.comment = try container.decode(Swift.String.self, forKey: .comment)
    self.id = try container.decode(Swift.String.self, forKey: .id)

    var publicKey: OneOf_PublicKey? = nil
    let publicKeyCheckAndSet = {
      if publicKey != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'publicKey'"))
      }
      publicKey = $0
    }
    if let asciiArmoredPgpPublicKey = try container.decodeIfPresent(
      Swift.String.self, forKey: .asciiArmoredPgpPublicKey)
    {
      try publicKeyCheckAndSet(.asciiArmoredPgpPublicKey(asciiArmoredPgpPublicKey))
    }
    if let pkixPublicKey = try container.decodeIfPresent(
      PkixPublicKey?.self, forKey: .pkixPublicKey)
    {
      try publicKeyCheckAndSet(.pkixPublicKey(pkixPublicKey))
    }
    self.publicKey = publicKey
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.comment, forKey: .comment)
    try container.encode(self.id, forKey: .id)

    if let choice = self.publicKey {
      switch choice {
      case .asciiArmoredPgpPublicKey(let value):
        try container.encode(value, forKey: .asciiArmoredPgpPublicKey)
      case .pkixPublicKey(let value):
        try container.encode(value, forKey: .pkixPublicKey)
      }
    }
  }

  public enum OneOf_PublicKey: Codable, Equatable, Sendable {
    /// ASCII-armored representation of a PGP public key, as the entire output by
    /// the command `gpg --export --armor foo@example.com` (either LF or CRLF
    /// line endings).
    /// When using this field, `id` should be left blank.  The BinAuthz API
    /// handlers will calculate the ID and fill it in automatically.  BinAuthz
    /// computes this ID as the OpenPGP RFC4880 V4 fingerprint, represented as
    /// upper-case hex.  If `id` is provided by the caller, it will be
    /// overwritten by the API-calculated ID.
    case asciiArmoredPgpPublicKey(Swift.String)
    /// A raw PKIX SubjectPublicKeyInfo format public key.
    ///
    /// NOTE: `id` may be explicitly provided by the caller when using this
    /// type of public key, but it MUST be a valid RFC3986 URI. If `id` is left
    /// blank, a default one will be computed based on the digest of the DER
    /// encoding of the public key.
    indirect case pkixPublicKey(PkixPublicKey?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.AttestorPublicKey"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
