// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleIAMV1
import GoogleCloudGax

extension Clients {
  protocol BinauthzManagementServiceV1Stub: Sendable {
    func getPolicy(
      request: GetPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryAuthorizationV1.Policy

    func updatePolicy(
      request: UpdatePolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryAuthorizationV1.Policy

    func createAttestor(
      request: CreateAttestorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryAuthorizationV1.Attestor

    func getAttestor(
      request: GetAttestorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryAuthorizationV1.Attestor

    func updateAttestor(
      request: UpdateAttestorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryAuthorizationV1.Attestor

    func listAttestors(
      request: ListAttestorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryAuthorizationV1.ListAttestorsResponse

    func deleteAttestor(
      request: DeleteAttestorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse
  }
}
