// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [BinauthzManagementServiceV1.CreateAttestor][google.cloud.binaryauthorization.v1.BinauthzManagementServiceV1.CreateAttestor].
///
/// [google.cloud.binaryauthorization.v1.BinauthzManagementServiceV1.CreateAttestor]: <doc:BinauthzManagementServiceV1/createAttestor(request:)>
public struct CreateAttestorRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent of this
  /// [attestor][google.cloud.binaryauthorization.v1.Attestor].
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var parent: Swift.String = Swift.String()

  /// Required. The [attestors][google.cloud.binaryauthorization.v1.Attestor] ID.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var attestorId: Swift.String = Swift.String()

  /// Required. The initial
  /// [attestor][google.cloud.binaryauthorization.v1.Attestor] value. The service
  /// will overwrite the [attestor
  /// name][google.cloud.binaryauthorization.v1.Attestor.name] field with the
  /// resource name, in the format `projects/*/attestors/*`.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  /// [google.cloud.binaryauthorization.v1.Attestor.name]: <doc:Attestor/name>
  public var attestor: Attestor? = nil

  /// Initialize a new instance of `CreateAttestorRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAttestorRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.CreateAttestorRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
