// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for [BinauthzManagementService.ListAttestors][].
public struct ListAttestorsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the project associated with the
  /// [attestors][google.cloud.binaryauthorization.v1.Attestor], in the format `projects/*`.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var parent: Swift.String = Swift.String()

  /// Requested page size. The server may return fewer results than requested. If
  /// unspecified, the server will pick an appropriate default.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A token identifying a page of results the server should return. Typically,
  /// this is the value of [ListAttestorsResponse.next_page_token][google.cloud.binaryauthorization.v1.ListAttestorsResponse.next_page_token] returned
  /// from the previous call to the `ListAttestors` method.
  ///
  /// [google.cloud.binaryauthorization.v1.ListAttestorsResponse.next_page_token]: <doc:ListAttestorsResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAttestorsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAttestorsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.binaryauthorization.v1.ListAttestorsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
