// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// BinAuthz Attestor verification
///
/// @Snippet(path: "ValidationHelperV1Quickstart")
public class ValidationHelperV1Client: Clients.ValidationHelperV1Protocol {
  let inner: any Clients.ValidationHelperV1Stub

  /// Creates a new `ValidationHelperV1Client` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.ValidationHelperV1Stub = try Clients.ValidationHelperV1Transport(options)
    inner = Clients.ValidationHelperV1Retry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ValidationHelperV1Logging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Returns whether the given Attestation for the given image URI
  /// was signed by the given Attestor
  ///
  /// @Snippet(path: "ValidationHelperV1_ValidateAttestationOccurrence")
  public func validateAttestationOccurrence(
    request: ValidateAttestationOccurrenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBinaryauthorizationV1.ValidateAttestationOccurrenceResponse {
    try await self.inner.validateAttestationOccurrence(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ValidationHelperV1Client`.
  ///
  /// To mock `ValidationHelperV1Client` change your functions to receive
  /// `some ValidationHelperV1Protocol` or `any ValidationHelperV1Protocol`
  /// and pass a mock implementation in your tests.
  public protocol ValidationHelperV1Protocol {
    /// See `ValidationHelperV1Client.validateAttestationOccurrence`.
    func validateAttestationOccurrence(request: ValidateAttestationOccurrenceRequest) async throws
      -> GoogleCloudBinaryauthorizationV1.ValidateAttestationOccurrenceResponse

    /// See `ValidationHelperV1Client.validateAttestationOccurrence`.
    func validateAttestationOccurrence(
      request: ValidateAttestationOccurrenceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBinaryauthorizationV1.ValidateAttestationOccurrenceResponse
  }
}

// Default implementations
extension Clients.ValidationHelperV1Protocol {
  public func validateAttestationOccurrence(request: ValidateAttestationOccurrenceRequest)
    async throws -> GoogleCloudBinaryauthorizationV1.ValidateAttestationOccurrenceResponse
  {
    try await self.validateAttestationOccurrence(request: request, options: .init())
  }

  public func validateAttestationOccurrence(
    request: ValidateAttestationOccurrenceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBinaryauthorizationV1.ValidateAttestationOccurrenceResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
