// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleGrafeasV1

/// Request message for
/// [ValidationHelperV1.ValidateAttestationOccurrence][google.cloud.binaryauthorization.v1.ValidationHelperV1.ValidateAttestationOccurrence].
///
/// [google.cloud.binaryauthorization.v1.ValidationHelperV1.ValidateAttestationOccurrence]: <doc:ValidationHelperV1/validateAttestationOccurrence(request:)>
public struct ValidateAttestationOccurrenceRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [Attestor][google.cloud.binaryauthorization.v1.Attestor] of the
  /// [occurrence][grafeas.v1.Occurrence], in the format
  /// `projects/*/attestors/*`.
  ///
  /// [google.cloud.binaryauthorization.v1.Attestor]: <doc:Attestor>
  public var attestor: Swift.String = Swift.String()

  /// Required. An [AttestationOccurrence][grafeas.v1.AttestationOccurrence] to
  /// be checked that it can be verified by the `Attestor`. It does not have to
  /// be an existing entity in Container Analysis. It must otherwise be a valid
  /// `AttestationOccurrence`.
  ///
  /// [grafeas.v1.AttestationOccurrence]: https://www.google.com/search?q=Swift+grafeas.v1+GoogleGrafeasV1.AttestationOccurrence
  public var attestation: GoogleGrafeasV1.AttestationOccurrence? = nil

  /// Required. The resource name of the [Note][grafeas.v1.Note] to which the
  /// containing [Occurrence][grafeas.v1.Occurrence] is associated.
  public var occurrenceNote: Swift.String = Swift.String()

  /// Required. The URI of the artifact (e.g. container image) that is the
  /// subject of the containing [Occurrence][grafeas.v1.Occurrence].
  public var occurrenceResourceUri: Swift.String = Swift.String()

  /// Initialize a new instance of `ValidateAttestationOccurrenceRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ValidateAttestationOccurrenceRequest().with { $0.attestor = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.binaryauthorization.v1.ValidateAttestationOccurrenceRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
